/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * gif.java
 *
 * Created on 05-ene-2015, 22:03:57
 */

package com.blogspot.rolandopalermo.sockets;

/**
 *
 * @author Wolfang M Salazar S
 */
public class gif extends javax.swing.JFrame {

    /** Creates new form gif */
    public gif() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/FIGURA1 - copia (2).gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 200, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/pantalla.png"))); // NOI18N
        jLabel1.setInheritsPopupMenu(false);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gif().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
