/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pantalla1.java
 *
 * Created on 03-ene-2015, 17:23:29
 */
package com.blogspot.rolandopalermo.sockets;

import com.blogspot.rolandopalermo.sockets.pantalla2;

/**
 *
 * @author Wolfang M Salazar S
 */
public class pantalla1 extends javax.swing.JFrame {

    /** Creates new form pantalla1 */
    public pantalla1() {
        initComponents();
        this.setSize(1050, 700);
        this.setLocation(5, 10);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 9));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CENTRO DE INVESTIGACIONES DE ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(730, 100, 180, 20);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14));
        jButton1.setText("ESTACION ERO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 330, 150, 90);

        jButton2.setFont(new java.awt.Font("Arial", 1, 14));
        jButton2.setText("ESTACION ERC");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(740, 330, 150, 90);

        jButton4.setBackground(new java.awt.Color(255, 51, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/boton2.png"))); // NOI18N
        jButton4.setText("ATRAS");
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(0, 590, 150, 70);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 9));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TELECOMUNICACIONES ELECTRONICAS");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(700, 110, 190, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 24));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BIENVENIDOS AL RADIOENLACE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 30, 400, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 36));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ORINOQUIA");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(230, 70, 270, 40);

        jLabel9.setFont(new java.awt.Font("Arial", 3, 30));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("INDIQUE LA ESTACION DE TRABAJO ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(200, 200, 560, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/PC2 - copia.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(650, 280, 420, 230);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/PC2 - copia.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(180, 280, 420, 230);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/LOGOS4 - copia.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(710, 0, 200, 110);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 30));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("EN LA CUAL SE ENCUENTRA");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(270, 240, 490, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/azul1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1150, 690);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BIENVENIDO AL RADIOENLACE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 40, 470, 40);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(820, 210, 240, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pantalla2 pan = new pantalla2();
        pan.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pantalla3 pan1 = new pantalla3();
        pan1.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        ventanita PT = new ventanita();
        PT.setVisible(true);
        dispose();
}//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new pantalla1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
