/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pantalla3.java
 *
 * Created on 04-ene-2015, 1:15:19
 */
package com.blogspot.rolandopalermo.sockets;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Wolfang M Salazar S
 */
public class pantalla3 extends javax.swing.JFrame {

    private String ip = "192.168.2.10";

    /** Creates new form pantalla3 */
    public pantalla3() {
        initComponents();
        this.setSize(1150, 690);
        this.setLocation(200, 10);
        setLocationRelativeTo(null);

        setVisible(true);



        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton4.setBackground(new java.awt.Color(255, 51, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/boton2.png"))); // NOI18N
        jButton4.setText("ATRAS");
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 570, 150, 70);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/bombillo.gif"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(190, 320, 10, 10);

        jTextField2.setBackground(new java.awt.Color(153, 153, 153));
        jTextField2.setFont(new java.awt.Font("Tahoma", 3, 18));
        jTextField2.setText("    Transmisión ");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(700, 550, 160, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 30));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("   Estación Remota ERC");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 120, 370, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18));
        jButton1.setText("Transmisión ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 480, 160, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/bombillo.gif"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(250, 360, 10, 10);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/bombillo.gif"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(870, 450, 10, 10);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/bombillo.gif"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(930, 410, 10, 10);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/bombillo.gif"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(940, 400, 10, 10);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/bombillo.gif"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(180, 310, 10, 10);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18));
        jButton2.setText("Recepción");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 530, 160, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/LOGOS4 - copia.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(870, 10, 290, 120);

        jTextField1.setBackground(new java.awt.Color(153, 153, 153));
        jTextField1.setFont(new java.awt.Font("Tahoma", 3, 18));
        jTextField1.setText("     Recepción");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(700, 600, 160, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 30));
        jLabel4.setText("   Estación Local ERO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(640, 190, 370, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/logo unexpo4.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 200, 150);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/animacion.gif"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(390, 220, 290, 210);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/pantallas_ondas.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1170, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        pantalla1 PT = new pantalla1();
        PT.setVisible(true);
        dispose();
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Acceder2Frames AF = new Acceder2Frames(ip);
        this.dispose();
        // AF.setVisible(true);
        AF.iniciarCaptura();
        AF.ejecutarCliente();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        

        Thread hilo = new Thread() {

            @Override
            public void run() {
                Server PT = new Server();
                PT.ejecutarServidor();
            }
        };
        hilo.start();
        dispose();


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new pantalla3().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
