/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pantalla2.java
 *
 * Created on 04-ene-2015, 0:23:39
 */
package com.blogspot.rolandopalermo.sockets;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Wolfang M Salazar S
 */
public class pantalla2 extends javax.swing.JFrame {

    private String ip = "192.168.2.10";

    /** Creates new form pantalla2 */
    public pantalla2() {
        initComponents();
        this.setSize(1150, 690);
        this.setLocation(200, 10);
        setLocationRelativeTo(null);

        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/logo unexpo4.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 0, 210, 180);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 30));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("   Estación Local ERO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 110, 370, 70);

        jTextField2.setBackground(new java.awt.Color(153, 153, 153));
        jTextField2.setFont(new java.awt.Font("Tahoma", 3, 18));
        jTextField2.setText("    Transmisión ");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(700, 550, 160, 30);

        jTextField1.setBackground(new java.awt.Color(153, 153, 153));
        jTextField1.setFont(new java.awt.Font("Tahoma", 3, 18));
        jTextField1.setText("     Recepción");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(700, 600, 160, 30);

        jButton5.setBackground(new java.awt.Color(255, 51, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/boton2.png"))); // NOI18N
        jButton5.setText("ATRAS");
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 570, 150, 70);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/bombillo.gif"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(180, 310, 10, 10);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/bombillo.gif"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(950, 400, 10, 10);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/bombillo.gif"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 340, 10, 10);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/bombillo.gif"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(960, 390, 10, 10);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/bombillo.gif"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(900, 430, 10, 10);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/bombillo.gif"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(190, 320, 10, 10);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/animacion.gif"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(390, 220, 290, 210);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18));
        jButton2.setText("Recepción");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 530, 160, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18));
        jButton1.setText("Transmisión ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 480, 160, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 30));
        jLabel5.setText("   Estación Remota ERC");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(610, 180, 370, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/LOGOS4 - copia.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(870, -10, 370, 170);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/pantallas_ondas.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1150, 690);

        jButton4.setBackground(new java.awt.Color(255, 51, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/boton2.png"))); // NOI18N
        jButton4.setText("ATRAS");
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(0, 560, 150, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        pantalla1 PT = new pantalla1();
        PT.setVisible(true);
        dispose();
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Acceder2Frames AF = new Acceder2Frames(ip);
        AF.iniciarCaptura();
        AF.ejecutarCliente();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        

        Thread hilo = new Thread() {

            @Override
            public void run() {
                Server PT = new Server();
                PT.ejecutarServidor();
            }
        };
        hilo.start();
        dispose();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        pantalla1 PT = new pantalla1();
        PT.setVisible(true);
        dispose();
}//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new pantalla2().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
