/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ventanita.java
 *
 * Created on 25-nov-2014, 8:33:44
 */

package com.blogspot.rolandopalermo.sockets;

import com.blogspot.rolandopalermo.sockets.ventanita;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import sun.security.util.Password;

/**
 *
 * @author Wolfang M Salazar S
 */
public class ventanita extends javax.swing.JFrame {

    /** Creates new form ventanita */
    public ventanita() {
        initComponents();
        setLocationRelativeTo(null);
      //  this.setExtendedState(ventanita.MAXIMIZED_BOTH);
        setTitle("PANTALLA PRINCIPAL");
        setLocationRelativeTo(null);
        this.setSize(1050,700);
        this.setVisible(true);
        this.setLocation(5,10);
        setResizable(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Entrar = new javax.swing.JButton();
        texto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        password1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(100, 100, 100));
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1103, 0);

        Entrar.setFont(new java.awt.Font("Tahoma", 1, 14));
        Entrar.setText("ENTRAR");
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });
        getContentPane().add(Entrar);
        Entrar.setBounds(700, 460, 110, 30);

        texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoActionPerformed(evt);
            }
        });
        texto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoKeyTyped(evt);
            }
        });
        getContentPane().add(texto);
        texto.setBounds(490, 430, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("UNIVERSIDAD NACIONAL EXPERIMENTAL POLITECNICA ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 30, 700, 20);

        password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password1ActionPerformed(evt);
            }
        });
        password1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                password1KeyTyped(evt);
            }
        });
        getContentPane().add(password1);
        password1.setBounds(490, 490, 180, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("\"ANTONIO JOSE DE SUCRE\"");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(400, 50, 230, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("VICE-RECTORADO PUERTO ORDAZ ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(370, 70, 310, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DEPARTAMENTO DE INGENIERIA ELECTRÓNICA");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 90, 420, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("LABORATORIO DE TELECOMUNICACIONES AVANZADAS");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(270, 110, 490, 20);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 14));
        jButton3.setText("USUARIO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(300, 430, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INTERFAZ DE USUARIO PARA LA TRANSMISION Y RECEPCION ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 320, 810, 50);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 24));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" DE VIDEO DIGITAL EN TIEMPO REAL Y EN FORMA REMOTA");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(200, 360, 750, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 14));
        jButton4.setText("CLAVE DE ACCESO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(300, 490, 170, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/antenacompleta2 - copia.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 40, 250, 240);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/antenacompleta.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(810, 40, 210, 240);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/azul1.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1140, 680);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/blogspot/rolandopalermo/sockets/antena2.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 20, 250, 250);

        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(560, 200, 70, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoActionPerformed

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed

         String USUARIO="administrador";
        String contraseña="telecom";

        String Pass=new String(password1.getPassword());



         if (texto.getText().equals(USUARIO)&& Pass.equals(contraseña)){

        pantalla1 pan=new pantalla1();
        pan.setVisible(true);
        dispose();
        }

        else{
             JOptionPane.showMessageDialog(this, "USUARIO Y/O CLAVE INCORRECTA PORFAVOR HAGA LAS CORRECCIONES", "Atención", JOptionPane.WARNING_MESSAGE, null);

     }

    }//GEN-LAST:event_EntrarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_password1ActionPerformed

    private void textoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoKeyTyped

         char cTeclaPresionada=evt.getKeyChar();
      if (cTeclaPresionada==KeyEvent.VK_ENTER) {
          Entrar.doClick();
      }
    }//GEN-LAST:event_textoKeyTyped

    private void password1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password1KeyTyped

            char cTeclaPresionada=evt.getKeyChar();
      if (cTeclaPresionada==KeyEvent.VK_ENTER) {
          Entrar.doClick();
      }
    }//GEN-LAST:event_password1KeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanita().setVisible(true);
        
                    }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entrar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField password1;
    private javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables

}
